# Generated by Django 5.0.3 on 2024-04-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_detail',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.BigIntegerField()),
                ('Emp_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=50)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BasicPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PAN', models.CharField(max_length=10)),
                ('UAN', models.BigIntegerField()),
                ('BankAccount', models.BigIntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGT_admin_app.depart')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGT_admin_app.employee_detail')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGT_admin_app.leavetype')),
            ],
        ),
    ]
