# Generated by Django 5.0.1 on 2024-04-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGT_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('payslip_pdf', models.FileField(upload_to='payslips/')),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGT_admin_app.employee_detail')),
            ],
        ),
    ]
